apiVersion: batch/v1
kind: Job
metadata:
  name: parallel-guidellm
  labels:
    app: guide-llm
spec:
  parallelism: ${N_WORKERS}
  completions: ${N_WORKERS}
  completionMode: Indexed
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: poker
    spec:
      restartPolicy: Never
      containers:
        - name: poker
          image: quay.io/tms/poker:0.0.10
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "16"
              memory: "64Gi"

          command: ["/bin/bash","-c"]
          args:
            - |
              # These are poorly behaved.
              #  --warmup-percent "0.20" \
              #  --cooldown-percent "0.20" \
              
              mkdir -p /guide-llm/${OUTPUT_PATH}
              echo "exec guidellm benchmark \
                --target "http://wide-ep-inference-gateway-istio.tms-llm-d-wide-ep.svc.cluster.local" \
                --rate-type constant \
                --max-requests "${NUM_REQUESTS}" \
                --rate "128" \
                --data '{"prompt_tokens": ${INPUT_LEN}, 
                         "output_tokens": ${OUTPUT_LEN},
                         "output_tokens_stdev": "200"}' \
                --output-path "/guide-llm/${OUTPUT_PATH}/${JOB_COMPLETION_INDEX}.json" \
                --output-sampling 500 \
                --disable-console-outputs \
                --disable-progress" > /guide-llm/${OUTPUT_PATH}/cmd

              
              exec guidellm benchmark \
                --target "http://wide-ep-inference-gateway-istio.tms-llm-d-wide-ep.svc.cluster.local" \
                --rate-type constant \
                --max-requests "${NUM_REQUESTS}" \
                --rate "128" \
                --data '{"prompt_tokens": ${INPUT_LEN}, 
                         "output_tokens": ${OUTPUT_LEN},
                         "output_tokens_stdev": "200"}' \
                --output-path "/guide-llm/${OUTPUT_PATH}/${JOB_COMPLETION_INDEX}.json" \
                --output-sampling 500 \
                --disable-console-outputs \
                --disable-progress

          env:
            - name: GUIDELLM__MAX_CONCURRENCY
              value: "${MAX_CONCURRENCY}"
            - name: GUIDELLM__REQUEST_TIMEOUT
              value: "900"
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HF_TOKEN
                  optional: true
          volumeMounts:
            - name: guide-llm
              mountPath: /guide-llm

      volumes:
        - name: guide-llm
          persistentVolumeClaim:
            claimName: guide-llm
