apiVersion: v1
kind: Pod
metadata:
  name: ${DEPLOY_USER}-vllm-dev
  labels:
    app: ${DEPLOY_USER}-vllm-dev
    llm-d.ai/owner: ${DEPLOY_USER}
spec:
  restartPolicy: Always
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.present
            operator: Exists
          - key: node-role.kubernetes.io/hpc-rack-2
            operator: Exists
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
    - name: dev
      image: quay.io/tms/vllm-dev:ef2c4f7
      imagePullPolicy: Always
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "32"
          memory: 512Gi
        limits:
          cpu: "32"
          memory: 512Gi
      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
              optional: true
        - name: HF_HOME
          value: /mnt/lustre/hf_cache
        - name: VLLM_CACHE_ROOT
          value: /mnt/lustre/${DEPLOY_USER}/vllm_cache_extdp
        - name: FLASHINFER_CACHE_DIR
          value: /mnt/lustre/${DEPLOY_USER}/flashinfer_cache_extdp
        - name: TORCH_CUDA_ARCH_LIST
          value: "9.0a;10.0+PTX"
        - name: CCACHE_DIR
          value: /mnt/lustre/${DEPLOY_USER}/ccache
        - name: CMAKE_CXX_COMPILER_LAUNCHER
          value: ccache
        - name: CMAKE_C_COMPILER_LAUNCHER
          value: ccache
      volumeMounts:
        - mountPath: /mnt/lustre
          name: lustre
        - mountPath: /dev/shm
          name: dshm
      workingDir: /mnt/lustre/${DEPLOY_USER}/vllm-dev
  volumes:
    - name: lustre
      persistentVolumeClaim:
        claimName: lustre-pvc-vllm
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 2Gi
