apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - decode-bench.yaml
  - serviceAccount.yaml
  - gateway.yaml
  - httproute.yaml

configMapGenerator:
  - name: jit-build-scripts
    options:
      disableNameSuffixHash: true
    files:
      - jit_mla_rope_quant.py
      - jit_mla_absorption_bmm.py
