apiVersion: v1
kind: Pod
metadata:
  name: ${POKER_NAME}
  labels:
    app: poker
    llm-d.ai/owner: ${DEPLOY_USER}

spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values: ["arm64", "amd64"]

  volumes:
    - name: lustre
      persistentVolumeClaim:
        claimName: lustre-pvc-vllm

  containers:
    - name: poker
      image: quay.io/tms/poker:0.0.15
      imagePullPolicy: Always
      stdin: true
      tty: true

      resources:
        limits:
          cpu: "16"
          memory: "64Gi"

      volumeMounts:
        - mountPath: /mnt/lustre
          name: lustre

      env:
        - name: LUSTRE_PREFIX
          value: /mnt/lustre/${DEPLOY_USER}
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
              optional: true

