apiVersion: v1
kind: ServiceAccount
metadata:
  name: poker
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: poker
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gateways"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: poker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: poker
subjects:
  - kind: ServiceAccount
    name: poker
---
apiVersion: v1
kind: Pod
metadata:
  name: poker
  labels:
    app: poker

spec:
  serviceAccountName: poker
  restartPolicy: Never
  nodeSelector:
    node.kubernetes.io/instance-type: BM.GPU.MI300X.8
  tolerations:
    - key: "amd.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"

  containers:
    - name: poker
      image: quay.io/tms/poker:0.0.13
      imagePullPolicy: Always
      command: ["/bin/bash", "-c"]
      args:
        - |
          uv pip install vllm
          exec sleep infinity
      stdin: true
      tty: true

      resources:
        limits:
          cpu: "16"
          memory: "64Gi"

      env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secret
              key: HF_TOKEN
              optional: true

